/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtChar123usernameChar125RouteImport } from './routes/@{$username}'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AtChar123usernameChar125IndexRouteImport } from './routes/@{$username}.index'
import { Route as AtChar123usernameChar125MemoIdRouteImport } from './routes/@{$username}.$memoId'
import { Route as ApiDevOtpRouteImport } from './routes/api/dev-otp'
import { Route as V1ClipsRouteImport } from './routes/v1/clips'
import { Route as V1MeRouteImport } from './routes/v1/me'
import { Route as V1MemosRouteImport } from './routes/v1/memos'
import { Route as V1StatsRouteImport } from './routes/v1/stats'
import { Route as V1TagsRouteImport } from './routes/v1/tags'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as V1MemosMemoIdRouteImport } from './routes/v1/memos/$memoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123usernameChar125Route =
  AtChar123usernameChar125RouteImport.update({
    id: '/@{$username}',
    path: '/@{$username}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123usernameChar125IndexRoute =
  AtChar123usernameChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123usernameChar125Route,
  } as any)
const AtChar123usernameChar125MemoIdRoute =
  AtChar123usernameChar125MemoIdRouteImport.update({
    id: '/$memoId',
    path: '/$memoId',
    getParentRoute: () => AtChar123usernameChar125Route,
  } as any)
const ApiDevOtpRoute = ApiDevOtpRouteImport.update({
  id: '/api/dev-otp',
  path: '/api/dev-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ClipsRoute = V1ClipsRouteImport.update({
  id: '/v1/clips',
  path: '/v1/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MeRoute = V1MeRouteImport.update({
  id: '/v1/me',
  path: '/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemosRoute = V1MemosRouteImport.update({
  id: '/v1/memos',
  path: '/v1/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StatsRoute = V1StatsRouteImport.update({
  id: '/v1/stats',
  path: '/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TagsRoute = V1TagsRouteImport.update({
  id: '/v1/tags',
  path: '/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1MemosMemoIdRoute = V1MemosMemoIdRouteImport.update({
  id: '/$memoId',
  path: '/$memoId',
  getParentRoute: () => V1MemosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@{$username}': typeof AtChar123usernameChar125RouteWithChildren
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/@{$username}/$memoId': typeof AtChar123usernameChar125MemoIdRoute
  '/api/dev-otp': typeof ApiDevOtpRoute
  '/v1/clips': typeof V1ClipsRoute
  '/v1/me': typeof V1MeRoute
  '/v1/memos': typeof V1MemosRouteWithChildren
  '/v1/stats': typeof V1StatsRoute
  '/v1/tags': typeof V1TagsRoute
  '/@{$username}/': typeof AtChar123usernameChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/memos/$memoId': typeof V1MemosMemoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/@{$username}/$memoId': typeof AtChar123usernameChar125MemoIdRoute
  '/api/dev-otp': typeof ApiDevOtpRoute
  '/v1/clips': typeof V1ClipsRoute
  '/v1/me': typeof V1MeRoute
  '/v1/memos': typeof V1MemosRouteWithChildren
  '/v1/stats': typeof V1StatsRoute
  '/v1/tags': typeof V1TagsRoute
  '/@{$username}': typeof AtChar123usernameChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/memos/$memoId': typeof V1MemosMemoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@{$username}': typeof AtChar123usernameChar125RouteWithChildren
  '/admin': typeof AdminRoute
  '/capture': typeof CaptureRoute
  '/explore': typeof ExploreRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/@{$username}/$memoId': typeof AtChar123usernameChar125MemoIdRoute
  '/api/dev-otp': typeof ApiDevOtpRoute
  '/v1/clips': typeof V1ClipsRoute
  '/v1/me': typeof V1MeRoute
  '/v1/memos': typeof V1MemosRouteWithChildren
  '/v1/stats': typeof V1StatsRoute
  '/v1/tags': typeof V1TagsRoute
  '/@{$username}/': typeof AtChar123usernameChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/v1/memos/$memoId': typeof V1MemosMemoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@{$username}'
    | '/admin'
    | '/capture'
    | '/explore'
    | '/interactions'
    | '/login'
    | '/notifications'
    | '/review'
    | '/settings'
    | '/signup'
    | '/@{$username}/$memoId'
    | '/api/dev-otp'
    | '/v1/clips'
    | '/v1/me'
    | '/v1/memos'
    | '/v1/stats'
    | '/v1/tags'
    | '/@{$username}/'
    | '/api/auth/$'
    | '/v1/memos/$memoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/capture'
    | '/explore'
    | '/interactions'
    | '/login'
    | '/notifications'
    | '/review'
    | '/settings'
    | '/signup'
    | '/@{$username}/$memoId'
    | '/api/dev-otp'
    | '/v1/clips'
    | '/v1/me'
    | '/v1/memos'
    | '/v1/stats'
    | '/v1/tags'
    | '/@{$username}'
    | '/api/auth/$'
    | '/v1/memos/$memoId'
  id:
    | '__root__'
    | '/'
    | '/@{$username}'
    | '/admin'
    | '/capture'
    | '/explore'
    | '/interactions'
    | '/login'
    | '/notifications'
    | '/review'
    | '/settings'
    | '/signup'
    | '/@{$username}/$memoId'
    | '/api/dev-otp'
    | '/v1/clips'
    | '/v1/me'
    | '/v1/memos'
    | '/v1/stats'
    | '/v1/tags'
    | '/@{$username}/'
    | '/api/auth/$'
    | '/v1/memos/$memoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtChar123usernameChar125Route: typeof AtChar123usernameChar125RouteWithChildren
  AdminRoute: typeof AdminRoute
  CaptureRoute: typeof CaptureRoute
  ExploreRoute: typeof ExploreRoute
  InteractionsRoute: typeof InteractionsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ApiDevOtpRoute: typeof ApiDevOtpRoute
  V1ClipsRoute: typeof V1ClipsRoute
  V1MeRoute: typeof V1MeRoute
  V1MemosRoute: typeof V1MemosRouteWithChildren
  V1StatsRoute: typeof V1StatsRoute
  V1TagsRoute: typeof V1TagsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$username}': {
      id: '/@{$username}'
      path: '/@{$username}'
      fullPath: '/@{$username}'
      preLoaderRoute: typeof AtChar123usernameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$username}/': {
      id: '/@{$username}/'
      path: '/'
      fullPath: '/@{$username}/'
      preLoaderRoute: typeof AtChar123usernameChar125IndexRouteImport
      parentRoute: typeof AtChar123usernameChar125Route
    }
    '/@{$username}/$memoId': {
      id: '/@{$username}/$memoId'
      path: '/$memoId'
      fullPath: '/@{$username}/$memoId'
      preLoaderRoute: typeof AtChar123usernameChar125MemoIdRouteImport
      parentRoute: typeof AtChar123usernameChar125Route
    }
    '/api/dev-otp': {
      id: '/api/dev-otp'
      path: '/api/dev-otp'
      fullPath: '/api/dev-otp'
      preLoaderRoute: typeof ApiDevOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/clips': {
      id: '/v1/clips'
      path: '/v1/clips'
      fullPath: '/v1/clips'
      preLoaderRoute: typeof V1ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/me': {
      id: '/v1/me'
      path: '/v1/me'
      fullPath: '/v1/me'
      preLoaderRoute: typeof V1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memos': {
      id: '/v1/memos'
      path: '/v1/memos'
      fullPath: '/v1/memos'
      preLoaderRoute: typeof V1MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/stats': {
      id: '/v1/stats'
      path: '/v1/stats'
      fullPath: '/v1/stats'
      preLoaderRoute: typeof V1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/tags': {
      id: '/v1/tags'
      path: '/v1/tags'
      fullPath: '/v1/tags'
      preLoaderRoute: typeof V1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/memos/$memoId': {
      id: '/v1/memos/$memoId'
      path: '/$memoId'
      fullPath: '/v1/memos/$memoId'
      preLoaderRoute: typeof V1MemosMemoIdRouteImport
      parentRoute: typeof V1MemosRoute
    }
  }
}

interface AtChar123usernameChar125RouteChildren {
  AtChar123usernameChar125MemoIdRoute: typeof AtChar123usernameChar125MemoIdRoute
  AtChar123usernameChar125IndexRoute: typeof AtChar123usernameChar125IndexRoute
}

const AtChar123usernameChar125RouteChildren: AtChar123usernameChar125RouteChildren =
  {
    AtChar123usernameChar125MemoIdRoute: AtChar123usernameChar125MemoIdRoute,
    AtChar123usernameChar125IndexRoute: AtChar123usernameChar125IndexRoute,
  }

const AtChar123usernameChar125RouteWithChildren =
  AtChar123usernameChar125Route._addFileChildren(
    AtChar123usernameChar125RouteChildren,
  )

interface V1MemosRouteChildren {
  V1MemosMemoIdRoute: typeof V1MemosMemoIdRoute
}

const V1MemosRouteChildren: V1MemosRouteChildren = {
  V1MemosMemoIdRoute: V1MemosMemoIdRoute,
}

const V1MemosRouteWithChildren =
  V1MemosRoute._addFileChildren(V1MemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtChar123usernameChar125Route: AtChar123usernameChar125RouteWithChildren,
  AdminRoute: AdminRoute,
  CaptureRoute: CaptureRoute,
  ExploreRoute: ExploreRoute,
  InteractionsRoute: InteractionsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ApiDevOtpRoute: ApiDevOtpRoute,
  V1ClipsRoute: V1ClipsRoute,
  V1MeRoute: V1MeRoute,
  V1MemosRoute: V1MemosRouteWithChildren,
  V1StatsRoute: V1StatsRoute,
  V1TagsRoute: V1TagsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
